import type { Service } from '@agency/types';
import { base, img } from './_shared';

const commonProcess = [
  { step: 1, title: 'Discovery & audit', description: 'We map your goals, audience, competitors and current performance baseline.' },
  { step: 2, title: 'Strategy', description: 'A prioritised plan with clear KPIs, timelines and owners.' },
  { step: 3, title: 'Build & launch', description: 'We produce the assets, ship the changes and instrument tracking.' },
  { step: 4, title: 'Optimise', description: 'Weekly iteration against the metrics that move revenue.' },
  { step: 5, title: 'Report', description: 'Plain-language reporting on what changed and what is next.' },
];

export const services: Service[] = [
  {
    ...base(1),
    id: 'svc-seo',
    slug: 'search-engine-optimization',
    title: 'Search Engine Optimization',
    tagline: 'Rank for the searches that bring buyers.',
    shortDescription:
      'Technical, on-page and content SEO that grows qualified organic traffic month over month.',
    description:
      'We start by understanding your business goals, brand voice, audience behaviour and competitive landscape, then execute a compounding SEO programme across technical health, on-page relevance, content and authority. Every sprint is tied to rankings, traffic and pipeline — not vanity metrics.',
    icon: 'Search',
    heroImage: { url: img('mo-seo'), alt: 'SEO dashboard', width: 1200, height: 800 },
    category: 'Organic',
    stats: [
      { label: 'Avg. organic growth', value: '2.7x' },
      { label: 'Keywords tracked', value: '1,000+' },
      { label: 'Content pieces / mo', value: '8' },
    ],
    features: [
      { title: 'Technical SEO', description: 'Crawlability, Core Web Vitals, indexation and site architecture.', icon: 'Wrench' },
      { title: 'On-page & content', description: 'Search-intent mapping, briefs and SEO-optimised publishing.', icon: 'FileText' },
      { title: 'Authority building', description: 'Digital PR and links from relevant, credible domains.', icon: 'Link2' },
      { title: 'Local SEO', description: 'Google Business Profile, citations and local landing pages.', icon: 'MapPin' },
    ],
    process: commonProcess,
    deliverables: ['Technical audit', 'Keyword & content roadmap', 'Monthly publishing', 'Rank & traffic reporting'],
    techStack: ['Ahrefs', 'Google Search Console', 'Screaming Frog', 'GA4'],
    faqs: [
      { question: 'How long until we see results?', answer: 'Early movement in 6–10 weeks; compounding gains from month 4 onward.' },
      { question: 'Do you write the content?', answer: 'Yes — briefs, drafts and publishing are included in every plan.' },
    ],
    seo: { title: 'Professional SEO Services', description: 'Data-driven SEO that grows qualified organic traffic and revenue.', keywords: ['seo agency', 'seo services'] },
  },
  {
    ...base(2),
    id: 'svc-google-ads',
    slug: 'google-ads',
    title: 'Google Ads',
    tagline: 'Your ROI partner on paid search.',
    shortDescription: 'Search, Performance Max and YouTube campaigns engineered for cost-efficient conversions.',
    description:
      'We build and run Google Ads accounts with adaptive bidding, tight query control and conversion tracking you can trust. Creative, landing pages and audiences are tested continuously so cost-per-acquisition trends down while volume holds.',
    icon: 'MousePointerClick',
    heroImage: { url: img('mo-gads'), alt: 'Google Ads campaign', width: 1200, height: 800 },
    category: 'Paid media',
    stats: [
      { label: 'Avg. CPA reduction', value: '-34%' },
      { label: 'Managed ad spend', value: '$2M+' },
      { label: 'Conversion lift', value: '+61%' },
    ],
    features: [
      { title: 'Search campaigns', description: 'Query mining, negative lists and message-match landing pages.', icon: 'Search' },
      { title: 'Performance Max', description: 'Asset groups and audience signals tuned to your best customers.', icon: 'Sparkles' },
      { title: 'Conversion tracking', description: 'Server-side tagging and offline conversion import.', icon: 'Target' },
      { title: 'Landing pages', description: 'Fast, focused pages built to convert paid traffic.', icon: 'LayoutTemplate' },
    ],
    process: commonProcess,
    deliverables: ['Account build / restructure', 'Tracking setup', 'Weekly optimisation', 'ROI reporting'],
    techStack: ['Google Ads', 'GA4', 'Google Tag Manager', 'Looker Studio'],
    faqs: [
      { question: 'What is the minimum ad budget?', answer: 'We recommend at least $1,000/mo in media to gather statistically useful data.' },
    ],
    seo: { title: 'Best Google Ads Agency', description: 'Cost-efficient Google Ads management with measurable ROI.', keywords: ['google ads agency', 'ppc'] },
  },
  {
    ...base(3),
    id: 'svc-facebook-ads',
    slug: 'facebook-ads',
    title: 'Facebook Advertising',
    tagline: 'Full-funnel Meta campaigns that scale.',
    shortDescription: 'Facebook and Instagram advertising combining strategy, creative, targeting and conversion tracking.',
    description:
      'We combine campaign strategy, scroll-stopping creative, audience targeting and reliable conversion tracking to make Meta a predictable acquisition channel — from cold prospecting to retention.',
    icon: 'Facebook',
    heroImage: { url: img('mo-meta'), alt: 'Meta Ads manager', width: 1200, height: 800 },
    category: 'Paid media',
    stats: [
      { label: 'Avg. ROAS', value: '4.3x' },
      { label: 'Creatives / month', value: '20+' },
      { label: 'Audiences tested', value: '50+' },
    ],
    features: [
      { title: 'Creative strategy', description: 'Hooks, angles and formats mapped to funnel stage.', icon: 'Clapperboard' },
      { title: 'Audience targeting', description: 'Prospecting, lookalikes and retention segments.', icon: 'Users' },
      { title: 'Conversions API', description: 'Server-side events for durable optimisation signal.', icon: 'ServerCog' },
      { title: 'Reporting', description: 'Blended metrics that reflect real business outcomes.', icon: 'BarChart3' },
    ],
    process: commonProcess,
    deliverables: ['Account & pixel setup', 'Creative production', 'Daily management', 'Weekly reporting'],
    techStack: ['Meta Ads Manager', 'Conversions API', 'Triple Whale', 'GA4'],
    faqs: [
      { question: 'Do you produce the ad creative?', answer: 'Yes — static, motion and UGC-style creative are part of the retainer.' },
    ],
    seo: { title: 'Facebook Advertising Agency', description: 'Full-funnel Meta advertising with creative and conversion tracking.', keywords: ['facebook ads agency', 'meta ads'] },
  },
  {
    ...base(4),
    id: 'svc-smm',
    slug: 'social-media-marketing',
    title: 'Social Media Marketing',
    tagline: 'Organic social that builds demand.',
    shortDescription: 'Conversion-centric organic social — content, community and paid amplification.',
    description:
      'A conversion-centric approach to organic social: a content engine mapped to your funnel, community management and selective paid amplification of what performs.',
    icon: 'Share2',
    heroImage: { url: img('mo-smm'), alt: 'Social content calendar', width: 1200, height: 800 },
    category: 'Organic',
    stats: [
      { label: 'Avg. engagement lift', value: '+120%' },
      { label: 'Posts / month', value: '16–24' },
      { label: 'Platforms', value: '4' },
    ],
    features: [
      { title: 'Content engine', description: 'Monthly calendar, scripting, design and scheduling.', icon: 'CalendarDays' },
      { title: 'Community management', description: 'Replies, DMs and reputation monitoring.', icon: 'MessagesSquare' },
      { title: 'Short-form video', description: 'Reels and TikToks built for reach.', icon: 'Video' },
      { title: 'Analytics', description: 'Monthly insight on what to double down on.', icon: 'LineChart' },
    ],
    process: commonProcess,
    deliverables: ['Content calendar', 'Design & copy', 'Community management', 'Monthly analytics'],
    techStack: ['Meta Business Suite', 'Buffer', 'CapCut', 'Canva'],
    faqs: [
      { question: 'Which platforms do you cover?', answer: 'Facebook, Instagram, LinkedIn and TikTok — prioritised by where your audience is.' },
    ],
    seo: { title: 'Social Media Marketing Agency', description: 'Conversion-focused organic social media management.', keywords: ['social media marketing', 'smm agency'] },
  },
  {
    ...base(5),
    id: 'svc-web',
    slug: 'web-design-and-development',
    title: 'Web Design & Development',
    tagline: 'Websites that bring you more leads, calls and sales.',
    shortDescription: 'SEO-friendly, conversion-focused websites — custom builds, e-commerce and maintenance.',
    description:
      'We design and build SEO-friendly websites focused on trust and business growth. From improved user experience and data protection to guaranteed satisfaction, our 6-step process takes startups from discovery to launch and long-term support.',
    icon: 'Code2',
    heroImage: { url: img('mo-web'), alt: 'Website design mockups', width: 1200, height: 800 },
    category: 'Build',
    stats: [
      { label: 'Years of experience', value: '10+' },
      { label: 'Projects delivered', value: '650+' },
      { label: 'Worldwide clients', value: '400+' },
    ],
    features: [
      { title: 'Custom website', description: 'Bespoke design and build on a modern, maintainable stack.', icon: 'PenTool' },
      { title: 'E-commerce', description: 'Storefronts engineered for conversion and average order value.', icon: 'ShoppingCart' },
      { title: 'Website maintenance', description: 'Updates, monitoring, backups and performance care.', icon: 'ShieldCheck' },
      { title: 'SEO-optimised', description: 'Fast Core Web Vitals and clean semantic markup from day one.', icon: 'Gauge' },
    ],
    process: [
      { step: 1, title: 'Discovery & business analysis', description: 'Goals, audiences, references and success criteria.' },
      { step: 2, title: 'User experience', description: 'Sitemap, flows and wireframes.' },
      { step: 3, title: 'User interface', description: 'Visual design system and high-fidelity screens.' },
      { step: 4, title: 'Development', description: 'Responsive, accessible front-end and integrations.' },
      { step: 5, title: 'Testing & QA', description: 'Cross-device, cross-browser and performance testing.' },
      { step: 6, title: 'Launch & support', description: 'Deploy, monitor and iterate.' },
    ],
    deliverables: ['UX wireframes', 'UI design system', 'Responsive build', 'CMS + training', 'Post-launch support'],
    techStack: ['Next.js', 'WordPress', 'Webflow', 'Shopify'],
    faqs: [
      { question: 'How long does a website take?', answer: 'A typical marketing site is 4–8 weeks depending on scope and content readiness.' },
      { question: 'Do you provide hosting?', answer: 'We set up managed hosting (Vercel or equivalent) and hand over full ownership.' },
      { question: 'Will the site be mobile-friendly?', answer: 'Every build is responsive and tested down to small screens.' },
    ],
    seo: { title: 'Web Design & Development Services', description: 'Conversion-focused, SEO-friendly websites for growing businesses.', keywords: ['web design', 'website development agency'] },
  },
  {
    ...base(6),
    id: 'svc-uiux',
    slug: 'ui-ux-design',
    title: 'UI/UX Design',
    tagline: 'Intuitive, conversion-focused product design.',
    shortDescription: 'Research-led interface design for websites, apps and SaaS products.',
    description:
      'We create intuitive, conversion-focused experiences grounded in research — user flows, design systems and prototypes that reduce friction and lift completion rates.',
    icon: 'Figma',
    heroImage: { url: img('mo-uiux'), alt: 'UI design system', width: 1200, height: 800 },
    category: 'Design',
    stats: [
      { label: 'Avg. task-completion lift', value: '+38%' },
      { label: 'Design systems shipped', value: '40+' },
      { label: 'Usability tests / project', value: '5+' },
    ],
    features: [
      { title: 'UX research', description: 'Interviews, journey mapping and heuristic audits.', icon: 'Microscope' },
      { title: 'Design systems', description: 'Reusable components with accessible defaults.', icon: 'Component' },
      { title: 'Prototyping', description: 'Interactive Figma prototypes for testing before build.', icon: 'MousePointer2' },
      { title: 'Handover', description: 'Dev-ready specs, tokens and documentation.', icon: 'FileCode2' },
    ],
    process: commonProcess,
    deliverables: ['Research findings', 'User flows', 'Design system', 'Prototype', 'Dev handoff'],
    techStack: ['Figma', 'Maze', 'Storybook'],
    faqs: [
      { question: 'Do you work from our existing brand?', answer: 'Yes — we extend your brand into a full interface system, or define one if needed.' },
    ],
    seo: { title: 'UI/UX Design Agency', description: 'Research-led, conversion-focused UI/UX design.', keywords: ['ui ux design agency', 'product design'] },
  },
  {
    ...base(7),
    id: 'svc-content',
    slug: 'content-writing',
    title: 'Content Writing',
    tagline: 'Words that rank and convert.',
    shortDescription: 'SEO blog writing, website copy and conversion copywriting.',
    description:
      'SEO blog writing, website content and copywriting produced by specialists — briefed against search intent, aligned to your brand voice and edited to a publishable standard.',
    icon: 'PenLine',
    heroImage: { url: img('mo-content'), alt: 'Editorial workspace', width: 1200, height: 800 },
    category: 'Organic',
    stats: [
      { label: 'Words / month', value: '20k+' },
      { label: 'Avg. time-on-page lift', value: '+45%' },
      { label: 'Editors per piece', value: '2' },
    ],
    features: [
      { title: 'SEO blog writing', description: 'Briefs, drafts and on-page optimisation.', icon: 'FileText' },
      { title: 'Website copy', description: 'Homepage, service and landing-page messaging.', icon: 'Type' },
      { title: 'Conversion copywriting', description: 'Offers, CTAs and email sequences.', icon: 'Megaphone' },
      { title: 'Editing', description: 'Two-pass editing for clarity and accuracy.', icon: 'SpellCheck' },
    ],
    process: commonProcess,
    deliverables: ['Content briefs', 'Drafts', 'Edited final copy', 'Meta & on-page'],
    techStack: ['Surfer', 'Grammarly', 'Google Docs'],
    faqs: [
      { question: 'Do you cover technical topics?', answer: 'Yes — we pair writers with subject-matter reviewers for accuracy.' },
    ],
    seo: { title: 'Content Writing Services', description: 'SEO content writing and conversion copywriting.', keywords: ['content writing services', 'seo copywriting'] },
  },
  {
    ...base(8),
    id: 'svc-brand',
    slug: 'brand-design',
    title: 'Brand Design',
    tagline: 'A brand identity that earns trust.',
    shortDescription: 'Positioning, identity systems and brand guidelines.',
    description:
      'We define how your brand looks, sounds and shows up — from positioning and naming to a complete identity system and usage guidelines your whole team can apply.',
    icon: 'Palette',
    heroImage: { url: img('mo-brand'), alt: 'Brand identity boards', width: 1200, height: 800 },
    category: 'Design',
    stats: [
      { label: 'Brands built', value: '120+' },
      { label: 'Guideline pages', value: '30–60' },
      { label: 'Concepts per project', value: '3' },
    ],
    features: [
      { title: 'Positioning', description: 'Audience, promise and messaging pillars.', icon: 'Compass' },
      { title: 'Identity system', description: 'Logo, type, colour, motifs and imagery direction.', icon: 'Shapes' },
      { title: 'Brand guidelines', description: 'A practical rulebook for consistent application.', icon: 'BookOpen' },
      { title: 'Asset kit', description: 'Templates for social, decks and print.', icon: 'Package' },
    ],
    process: commonProcess,
    deliverables: ['Positioning doc', 'Identity system', 'Guidelines', 'Template kit'],
    techStack: ['Figma', 'Adobe Illustrator', 'Adobe InDesign'],
    faqs: [
      { question: 'Can you refresh an existing brand?', answer: 'Yes — evolution projects keep equity while modernising the system.' },
    ],
    seo: { title: 'Brand Design Agency', description: 'Positioning and identity systems that build trust.', keywords: ['brand design agency', 'branding'] },
  },
  {
    ...base(9),
    id: 'svc-graphics',
    slug: 'graphics-design',
    title: 'Graphics Design',
    tagline: 'On-brand creative, on demand.',
    shortDescription: 'Marketing collateral, social creative, infographics and product graphics.',
    description:
      'Unlimited-style creative production for growing teams — social graphics, ad creative, infographics, pitch decks and packaging, all tightly on-brand and delivered fast.',
    icon: 'Image',
    heroImage: { url: img('mo-graphics'), alt: 'Graphic design samples', width: 1200, height: 800 },
    category: 'Design',
    stats: [
      { label: 'Turnaround', value: '24–48h' },
      { label: 'Assets / month', value: '60+' },
      { label: 'Revisions', value: 'Unlimited' },
    ],
    features: [
      { title: 'Social & ad creative', description: 'Statics and carousels sized for every placement.', icon: 'LayoutGrid' },
      { title: 'Infographics', description: 'Data and process visuals that are easy to grasp.', icon: 'PieChart' },
      { title: 'Presentations', description: 'Investor and sales decks that look the part.', icon: 'Presentation' },
      { title: 'Product graphics', description: 'Packaging, labels and marketplace imagery.', icon: 'Box' },
    ],
    process: commonProcess,
    deliverables: ['Creative queue', 'Source files', 'Brand-locked templates'],
    techStack: ['Adobe Photoshop', 'Adobe Illustrator', 'Figma'],
    faqs: [
      { question: 'How do requests work?', answer: 'Submit briefs to a shared queue; we deliver in 24–48h per item.' },
    ],
    seo: { title: 'Graphic Design Services', description: 'Fast, on-brand graphic design for marketing teams.', keywords: ['graphic design agency', 'graphics design'] },
  },
  {
    ...base(10),
    id: 'svc-motion',
    slug: 'motion-graphics',
    title: 'Motion Graphics',
    tagline: 'Motion that explains and sells.',
    shortDescription: 'Explainers, product demos, ad cutdowns and animated social content.',
    description:
      'From explainer videos and product demos to paid ad cutdowns and animated social posts — we script, storyboard, design and animate video that communicates fast.',
    icon: 'Clapperboard',
    heroImage: { url: img('mo-motion'), alt: 'Motion graphics frames', width: 1200, height: 800 },
    category: 'Design',
    stats: [
      { label: 'Avg. view-through lift', value: '+52%' },
      { label: 'Videos / month', value: '8–12' },
      { label: 'Formats', value: '6+' },
    ],
    features: [
      { title: 'Explainers', description: 'Script-to-screen animated explainers.', icon: 'Film' },
      { title: 'Product demos', description: 'Screen-capture and UI animation.', icon: 'MonitorPlay' },
      { title: 'Ad cutdowns', description: '6s / 15s / 30s versions from one master.', icon: 'Scissors' },
      { title: 'Social motion', description: 'Looping, captioned posts and stories.', icon: 'Repeat' },
    ],
    process: commonProcess,
    deliverables: ['Script & storyboard', 'Design frames', 'Animation', 'Platform exports'],
    techStack: ['Adobe After Effects', 'Adobe Premiere Pro', 'Figma'],
    faqs: [
      { question: 'Do you write scripts?', answer: 'Yes — scripting and storyboarding are included.' },
    ],
    seo: { title: 'Motion Graphics Services', description: 'Explainers, demos and animated social video.', keywords: ['motion graphics agency', 'video animation'] },
  },
];
