/**
 * Generator: colors/palette.mjs  ->  tailwind/tokens.css  +  colors/index.ts
 *
 * Run:  pnpm --filter @agency/config gen   (also runs as the package's `build`)
 *
 * No dependencies — the oklch -> sRGB hex conversion is inlined below
 * (Björn Ottosson's OKLab matrices) so the package everything depends on
 * stays dependency-free.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { semantic, ramps, chart, radius, BRAND_HUE } from './palette.mjs';

const HERE = dirname(fileURLToPath(import.meta.url));
const CONFIG_ROOT = join(HERE, '..');

/* ── colour maths ─────────────────────────────────────────────────────────── */

const OKLCH_RE =
  /oklch\(\s*([\d.]+%?)\s+([\d.]+%?)\s+(-?[\d.]+)(?:\s*\/\s*([\d.]+%?))?\s*\)/i;

/** @param {string} str @returns {{L:number,C:number,H:number,a:number}} */
function parseOklch(str) {
  const m = OKLCH_RE.exec(str.trim());
  if (!m) throw new Error(`Not an oklch() colour: ${str}`);
  const num = (v, pctScale = 1) =>
    v.endsWith('%') ? (parseFloat(v) / 100) * pctScale : parseFloat(v);
  return {
    L: num(m[1]),
    C: num(m[2], 0.4),
    H: parseFloat(m[3]),
    a: m[4] == null ? 1 : num(m[4]),
  };
}

const clamp01 = (n) => Math.min(1, Math.max(0, n));

function oklchToRgb({ L, C, H }) {
  const h = (H * Math.PI) / 180;
  const a = C * Math.cos(h);
  const b = C * Math.sin(h);

  const l_ = L + 0.3963377774 * a + 0.2158037573 * b;
  const m_ = L - 0.1055613458 * a - 0.0638541728 * b;
  const s_ = L - 0.089484178 * a - 1.291485548 * b;

  const l = l_ ** 3;
  const m = m_ ** 3;
  const s = s_ ** 3;

  const lin = [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ];

  return lin.map((c) => {
    const v = c <= 0.0031308 ? 12.92 * c : 1.055 * Math.pow(c, 1 / 2.4) - 0.055;
    return clamp01(v);
  });
}

const channelHex = (n) =>
  Math.round(n * 255)
    .toString(16)
    .padStart(2, '0');

/** oklch() string -> #rrggbb (or #rrggbbaa when alpha < 1). */
function oklchToHex(str) {
  const parsed = parseOklch(str);
  const [r, g, b] = oklchToRgb(parsed);
  let hex = `#${channelHex(r)}${channelHex(g)}${channelHex(b)}`;
  if (parsed.a < 1) hex += channelHex(parsed.a);
  return hex;
}

/* ── numeric ramps ───────────────────────────────────────────────────────── */

const STOPS = [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];
// Fixed lightness per stop; chroma is the seed's chroma times a bell factor.
const RAMP_L = {
  50: 0.985, 100: 0.96, 200: 0.915, 300: 0.85, 400: 0.74,
  500: 0.63, 600: 0.55, 700: 0.47, 800: 0.4, 900: 0.31, 950: 0.22,
};
const RAMP_C = {
  50: 0.12, 100: 0.24, 200: 0.42, 300: 0.66, 400: 0.9,
  500: 1.0, 600: 1.0, 700: 0.92, 800: 0.8, 900: 0.62, 950: 0.45,
};

/** @param {string} seed oklch() @returns {Record<number,string>} stop -> oklch() */
function buildRamp(seed) {
  const { C, H } = parseOklch(seed);
  /** @type {Record<number,string>} */
  const out = {};
  for (const stop of STOPS) {
    const c = +(C * RAMP_C[stop]).toFixed(4);
    out[stop] = `oklch(${RAMP_L[stop]} ${c} ${H})`;
  }
  return out;
}

/* ── build the maps ──────────────────────────────────────────────────────── */

const kebab = (k) => k.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

const rampPrimary = buildRamp(ramps.primary);
const rampNeutral = buildRamp(ramps.neutral);

const radiusRem = {
  base: `${radius}rem`,
  sm: `calc(${radius}rem - 4px)`,
  md: `calc(${radius}rem - 2px)`,
  lg: `${radius}rem`,
  xl: `calc(${radius}rem + 4px)`,
};

/* ── emit tokens.css ─────────────────────────────────────────────────────── */

const GEN_WARNING = `/*
 * GENERATED by colors/generate.mjs from colors/palette.mjs — DO NOT EDIT.
 * Edit colors/palette.mjs, then run: pnpm --filter @agency/config gen
 *
 * @agency/config — shared design tokens (Tailwind v4). Import AFTER tailwindcss:
 *   @import 'tailwindcss';
 *   @import '@agency/config/tailwind/tokens.css';
 *
 * Semantic tokens (--primary, --muted, …) are theme-aware: light on :root,
 * dark on .dark. The numeric scales (--color-primary-50…950, --color-neutral-*)
 * are absolute — they do NOT change with the theme; use them for bespoke tints.
 */`;

const semanticBlock = (set) =>
  Object.entries(set)
    .map(([k, v]) => `  --${kebab(k)}: ${v};`)
    .join('\n');

const chartBlock = (arr) => arr.map((v, i) => `  --chart-${i + 1}: ${v};`).join('\n');

const themeInlineColors = [
  ...Object.keys(semantic.light).map(
    (k) => `  --color-${kebab(k)}: var(--${kebab(k)});`
  ),
  ...[1, 2, 3, 4, 5].map((n) => `  --color-chart-${n}: var(--chart-${n});`),
].join('\n');

const scaleBlock = (name, ramp) =>
  STOPS.map((s) => `  --color-${name}-${s}: ${ramp[s]};`).join('\n');

const css = `${GEN_WARNING}

@custom-variant dark (&:is(.dark *));

:root {
  --radius: ${radius}rem;

${semanticBlock(semantic.light)}

${chartBlock(chart.light)}
}

.dark {
${semanticBlock(semantic.dark)}

${chartBlock(chart.dark)}
}

@theme inline {
${themeInlineColors}

  --radius-sm: ${radiusRem.sm};
  --radius-md: ${radiusRem.md};
  --radius-lg: ${radiusRem.lg};
  --radius-xl: ${radiusRem.xl};

  --font-sans:
    var(--font-geist-sans), ui-sans-serif, system-ui, -apple-system, 'Segoe UI', Roboto, sans-serif;
  --font-mono: var(--font-geist-mono), ui-monospace, 'SFMono-Regular', Menlo, monospace;
}

/* Absolute tint/shade scales — do not theme-switch. Brand hue ${BRAND_HUE}. */
@theme {
${scaleBlock('primary', rampPrimary)}

${scaleBlock('neutral', rampNeutral)}
}
`;

writeFileSync(join(CONFIG_ROOT, 'tailwind', 'tokens.css'), css);

/* ── emit colors/index.ts ────────────────────────────────────────────────── */

const hexSet = (set) =>
  Object.fromEntries(Object.entries(set).map(([k, v]) => [k, oklchToHex(v)]));

const hexRamp = (ramp) =>
  Object.fromEntries(STOPS.map((s) => [s, oklchToHex(ramp[s])]));

const obj = (record, indent = 4) => {
  const pad = ' '.repeat(indent);
  return Object.entries(record)
    .map(([k, v]) => `${pad}${/^\d/.test(k) ? `'${k}'` : k}: '${v}',`)
    .join('\n');
};

const ts = `/* eslint-disable */
/*
 * GENERATED by colors/generate.mjs from colors/palette.mjs — DO NOT EDIT.
 * Edit colors/palette.mjs, then run: pnpm --filter @agency/config gen
 *
 * Typed palette for code that needs a colour VALUE (not a Tailwind class):
 * viewport themeColor, OG images, transactional email, chart libraries.
 * For anything rendered as HTML/JSX, prefer the Tailwind utilities backed by
 * tailwind/tokens.css (bg-primary, text-muted-foreground, …).
 */

export const colors = {
  /** Light-theme semantic colours, as #rrggbb (a few #rrggbbaa). */
  light: {
${obj(hexSet(semantic.light))}
  },
  /** Dark-theme semantic colours. */
  dark: {
${obj(hexSet(semantic.dark))}
  },
  /** Absolute tint/shade scales (theme-independent). */
  scale: {
    primary: {
${obj(hexRamp(rampPrimary), 6)}
    },
    neutral: {
${obj(hexRamp(rampNeutral), 6)}
    },
  },
  /** Categorical chart colours. */
  chart: {
    light: [${chart.light.map((v) => `'${oklchToHex(v)}'`).join(', ')}],
    dark: [${chart.dark.map((v) => `'${oklchToHex(v)}'`).join(', ')}],
  },
  /** Raw oklch() strings, if you need wide-gamut values. */
  oklch: {
    light: {
${obj(semantic.light, 6)}
    },
    dark: {
${obj(semantic.dark, 6)}
    },
  },
  radius: {
    base: '${radiusRem.base}',
    sm: '${radiusRem.sm}',
    md: '${radiusRem.md}',
    lg: '${radiusRem.lg}',
    xl: '${radiusRem.xl}',
  },
} as const;

export type Colors = typeof colors;
export type SemanticColorName = keyof Colors['light'];

/** \`cssVar('primary')\` / \`cssVar('mutedForeground')\` -> \`'var(--muted-foreground)'\`
 *  — for style props that should track the live theme token, not a frozen hex.
 *  Pass a {@link SemanticColorName} (or any custom token name). */
export const cssVar = (name: SemanticColorName | string): string =>
  \`var(--\${String(name).replace(/[A-Z]/g, (c) => '-' + c.toLowerCase())})\`;
`;

writeFileSync(join(CONFIG_ROOT, 'colors', 'index.ts'), ts);

console.log('✓ wrote tailwind/tokens.css and colors/index.ts');
