 
/*
 * GENERATED by colors/generate.mjs from colors/palette.mjs — DO NOT EDIT.
 * Edit colors/palette.mjs, then run: pnpm --filter @agency/config gen
 *
 * Typed palette for code that needs a colour VALUE (not a Tailwind class):
 * viewport themeColor, OG images, transactional email, chart libraries.
 * For anything rendered as HTML/JSX, prefer the Tailwind utilities backed by
 * tailwind/tokens.css (bg-primary, text-muted-foreground, …).
 */

export const colors = {
  /** Light-theme semantic colours, as #rrggbb (a few #rrggbbaa). */
  light: {
    background: '#ffffff',
    foreground: '#090d16',
    card: '#ffffff',
    cardForeground: '#090d16',
    popover: '#ffffff',
    popoverForeground: '#090d16',
    primary: '#3d77d7',
    primaryForeground: '#f8fafe',
    secondary: '#f2f4f9',
    secondaryForeground: '#161b24',
    muted: '#f2f4f9',
    mutedForeground: '#636975',
    accent: '#e8effc',
    accentForeground: '#131a29',
    destructive: '#e01e23',
    destructiveForeground: '#f8fafe',
    success: '#009962',
    successForeground: '#f5fcf8',
    warning: '#dfa11a',
    warningForeground: '#362607',
    border: '#e3e5e9',
    input: '#e3e5e9',
    ring: '#3d77d7',
    brandNavy: '#1b2844',
    brandNavyForeground: '#f2f5fc',
  },
  /** Dark-theme semantic colours. */
  dark: {
    background: '#090d16',
    foreground: '#f2f5fc',
    card: '#111620',
    cardForeground: '#f2f5fc',
    popover: '#111620',
    popoverForeground: '#f2f5fc',
    primary: '#6193ff',
    primaryForeground: '#090d16',
    secondary: '#202633',
    secondaryForeground: '#f2f5fc',
    muted: '#202633',
    mutedForeground: '#9298a5',
    accent: '#262e3d',
    accentForeground: '#f2f5fc',
    destructive: '#f0574e',
    destructiveForeground: '#f2f5fc',
    success: '#2eb27a',
    successForeground: '#05160d',
    warning: '#edb345',
    warningForeground: '#1f1401',
    border: '#ffffff1f',
    input: '#ffffff26',
    ring: '#6193ff',
    brandNavy: '#101a2f',
    brandNavyForeground: '#f2f5fc',
  },
  /** Absolute tint/shade scales (theme-independent). */
  scale: {
    primary: {
      '50': '#f3fbff',
      '100': '#e3f3ff',
      '200': '#c9e4ff',
      '300': '#a5cfff',
      '400': '#74aaff',
      '500': '#4c87e8',
      '600': '#346ecd',
      '700': '#2357ac',
      '800': '#19448b',
      '900': '#0e2e61',
      '950': '#05193b',
    },
    neutral: {
      '50': '#fafafb',
      '100': '#f1f2f4',
      '200': '#e1e3e6',
      '300': '#cbced3',
      '400': '#a7abb2',
      '500': '#858991',
      '600': '#6e7279',
      '700': '#585b61',
      '800': '#45484d',
      '900': '#2e3034',
      '950': '#191b1d',
    },
  },
  /** Categorical chart colours. */
  chart: {
    light: ['#497ef7', '#00b1aa', '#8f54dc', '#e99b2a', '#ec4764'],
    dark: ['#6799ff', '#30c6bf', '#ab79f5', '#f7ac4d', '#ff6d80'],
  },
  /** Raw oklch() strings, if you need wide-gamut values. */
  oklch: {
    light: {
      background: 'oklch(1 0 0)',
      foreground: 'oklch(0.16 0.02 264)',
      card: 'oklch(1 0 0)',
      cardForeground: 'oklch(0.16 0.02 264)',
      popover: 'oklch(1 0 0)',
      popoverForeground: 'oklch(0.16 0.02 264)',
      primary: 'oklch(0.58 0.16 260)',
      primaryForeground: 'oklch(0.985 0.005 264)',
      secondary: 'oklch(0.968 0.007 264)',
      secondaryForeground: 'oklch(0.22 0.02 264)',
      muted: 'oklch(0.968 0.007 264)',
      mutedForeground: 'oklch(0.52 0.02 264)',
      accent: 'oklch(0.95 0.02 264)',
      accentForeground: 'oklch(0.22 0.03 264)',
      destructive: 'oklch(0.58 0.223 27)',
      destructiveForeground: 'oklch(0.985 0.005 264)',
      success: 'oklch(0.6 0.14 160)',
      successForeground: 'oklch(0.985 0.01 160)',
      warning: 'oklch(0.75 0.15 80)',
      warningForeground: 'oklch(0.28 0.05 80)',
      border: 'oklch(0.922 0.006 264)',
      input: 'oklch(0.922 0.006 264)',
      ring: 'oklch(0.58 0.16 260)',
      brandNavy: 'oklch(0.28 0.055 264)',
      brandNavyForeground: 'oklch(0.97 0.01 264)',
    },
    dark: {
      background: 'oklch(0.16 0.02 264)',
      foreground: 'oklch(0.97 0.01 264)',
      card: 'oklch(0.2 0.022 264)',
      cardForeground: 'oklch(0.97 0.01 264)',
      popover: 'oklch(0.2 0.022 264)',
      popoverForeground: 'oklch(0.97 0.01 264)',
      primary: 'oklch(0.68 0.17 264)',
      primaryForeground: 'oklch(0.16 0.02 264)',
      secondary: 'oklch(0.27 0.025 264)',
      secondaryForeground: 'oklch(0.97 0.01 264)',
      muted: 'oklch(0.27 0.025 264)',
      mutedForeground: 'oklch(0.68 0.02 264)',
      accent: 'oklch(0.3 0.03 264)',
      accentForeground: 'oklch(0.97 0.01 264)',
      destructive: 'oklch(0.66 0.19 27)',
      destructiveForeground: 'oklch(0.97 0.01 264)',
      success: 'oklch(0.68 0.14 160)',
      successForeground: 'oklch(0.18 0.03 160)',
      warning: 'oklch(0.8 0.14 80)',
      warningForeground: 'oklch(0.2 0.04 80)',
      border: 'oklch(1 0 0 / 12%)',
      input: 'oklch(1 0 0 / 15%)',
      ring: 'oklch(0.68 0.17 264)',
      brandNavy: 'oklch(0.22 0.045 264)',
      brandNavyForeground: 'oklch(0.97 0.01 264)',
    },
  },
  radius: {
    base: '0.625rem',
    sm: 'calc(0.625rem - 4px)',
    md: 'calc(0.625rem - 2px)',
    lg: '0.625rem',
    xl: 'calc(0.625rem + 4px)',
  },
} as const;

export type Colors = typeof colors;
export type SemanticColorName = keyof Colors['light'];

/** `cssVar('primary')` / `cssVar('mutedForeground')` -> `'var(--muted-foreground)'`
 *  — for style props that should track the live theme token, not a frozen hex.
 *  Pass a {@link SemanticColorName} (or any custom token name). */
export const cssVar = (name: SemanticColorName | string): string =>
  `var(--${String(name).replace(/[A-Z]/g, (c) => '-' + c.toLowerCase())})`;
